### ISSUE TITLE
Character encoding in dct:description

### ISSUE THREAD

**Issue by Polymathronic** [YourDataStories/harvesters#11]
E.g. http://linkedeconomy.org/resource/Contract/53655 (could be in the input data; please check).

**Comment by mogaio** [comment]
It's an issue in the input data

**Comment by Polymathronic** [comment]
Does it affect only this property? If yes, then you can simply HTML-decode such characters.

**Comment by mogaio** [comment]
Yes it's just affect this property, we will add a HTML decoder to solve this issue okay.

**Comment by mogaio** [comment]
A HTML decoder added to the pipeline.
