### ISSUE TITLE
Organizations vs. OrganizationalUnits

### ISSUE THREAD

**Issue by Polymathronic** [YourDataStories/harvesters#13]
I see you have some resources such as http://linkedeconomy.org/resource/OrganizationUnit/FAIRGmbH declared as Organizations, even though the resource URI implies it's an OrganizationUnit.

See also https://github.com/YourDataStories/harvesters/issues/14

**Comment by mogaio** [comment]
This issue is fixed now, https://github.com/YourDataStories/harvesters/issues/14#issuecomment-208290024
