### ISSUE TITLE
pc:mainObject vs elod:hasCpv

### ISSUE THREAD

**Issue by giorgosvaf** [YourDataStories/harvesters#17]
According to our specification in the following google spreadsheet please use just pc:mainObject in order to link Contracts with CPVs and not elod:hasCpv

https://docs.google.com/spreadsheets/d/1xMiTAk7mXhGPnSU4-qspiYaN15ur4v3J0lU8qYODtzk/edit#gid=481927591

Query with current results,
select distinct \* 
from http://yourdatastories.eu/pilot3 
where {
?s elod:hasCpv ?p ; pc:mainObject ?o
}

**Comment by mogaio** [comment]
We fixed this issue in the latest version of the rdf data.
