### ISSUE TITLE
gr:hasCurrencyValue has rdfs:range xsd:float

### ISSUE THREAD

**Issue by giorgosvaf** [YourDataStories/harvesters#18]
Please change the datatype value of gr:hasCurrencyValue to xsd:float.

select distinct \* 
from http://yourdatastories.eu/pilot3 
where {
?s gr:hasCurrencyValue ?p
}

**Comment by mogaio** [comment]
We fixed this issue in the latest version of the rdf data.

**Comment by Polymathronic** [comment]
The current version of the data says otherwise:

```
PREFIX gr: <http://purl.org/goodrelations/v1#>

SELECT ?value ?type FROM <http://yourdatastories.eu/pilot3>
WHERE {
  ?s gr:hasCurrencyValue ?value.
  BIND(DATATYPE(?value) as ?type)
}
```

**Comment by mogaio** [comment]
There was an issue in the code that caused this issue for part of the gr:hasCurrencyValue datatype, now it's fixed.
