### ISSUE TITLE
elod:countryIsoCode

### ISSUE THREAD

**Issue by Polymathronic** [YourDataStories/harvesters#20]
As we don't have the exact address information for all organizations, we tend to attach the countries directly to organizations, rather than addresses. The vCard ontology does have the `country-name` datatype property for describing the country of an address, but I would say it's redundant in this case.

**Comment by mogaio** [comment]
we currently depend on the elod:countryIsoCode in expending our sparql quires so we would prefer to keep it like this unless you see it important to change it.

**Comment by Polymathronic** [comment]
I don't think your data should ever depend on your queries (unless you're optimizing for performance, and you have a really good case for it). We need to align the three pilots, so I suggest you change it.

**Comment by mogaio** [comment]
we applied your comment in the latest version to make it better aligned to the other pilots, it is uploaded to the triple store now.

**Comment by Polymathronic** [comment]
What exactly did you change? I don't see the proposed changes in the pilot 3 graph.
