### ISSUE TITLE
skos:Concepts with wrong IRI base

### ISSUE THREAD

**Issue by Polymathronic** [YourDataStories/harvesters#28]
`http://linkedeconomy.org/ontology#LowValue` and `http://linkedeconomy.org/ontology#Studies` use the TBox (`elod`) prefix instead of the `http://linkedeconomy.org/resource/` one.

**Comment by giorgosvaf** [comment]
http://linkedeconomy.org/ontology#Studies is actually a concept of concept scheme Kinds just like http://purl.org/procurement/public-contracts-kinds#Supplies and that's why we did it that way.

Why is important to change it?

**Comment by Polymathronic** [comment]
My opinion is that the `ontology` namespace should remain reserved for the TBox (that would also be in line with our approach so far). The two concepts are `skos:Concept` **individuals** (ABox), so I believe they belong in the `resource` namespace, along with all other individuals. Right now, they are the only `skos:Concepts` using the `elod` prefix.

**Comment by giorgosvaf** [comment]
It's ok now.

Please check the following queries,

select distinct \* from <http://yourdatastories.eu/NSRF/Diavgeia> where {<http://linkedeconomy.org/resource/Kind/Studies> ?p ?o} 

select distinct \* from <http://yourdatastories.eu/NSRF/Diavgeia> where {<http://linkedeconomy.org/resource/ProcedureType/LowValue> ?p ?o}
