### ISSUE TITLE
Updates for OC Harvester

### ISSUE THREAD

**Issue by vafopoulos** [YourDataStories/harvesters#29]
It would be useful also here https://github.com/YourDataStories/harvesters/tree/master/Pilot2/OpenCorporatesHarvester to have a README file to state how it works and the underlying workflows. Also a first indication of performance statistics

**Comment by Polymathronic** [comment]
It's merely a script that fetches a list of URLs from the OC website. The processing time is <1s per URL. I provided simple instructions (the rest should be rather straight-forward).
