### ISSUE TITLE
BusinessEntity URIs

### ISSUE THREAD

**Issue by Polymathronic** [YourDataStories/harvesters#8]
It appears some business entities don't have identifiers (i.e. the URIs are missing the last bit of the path). Please try the following query:

`SELECT * WHERE {<http://linkedeconomy.org/resource/BusinessEntity/> ?p ?o}`

**Comment by Polymathronic** [comment]
Split into two separate issues. See: https://github.com/YourDataStories/harvesters/issues/9

**Comment by mogaio** [comment]
It was an encoding issue that appeared with the Greek letters, we solved this issue by hashing the identifiers (business entities/ organization names).
